name: Test Self-Hosted Runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run shell command
      run: echo "Self-hosted runner is working!"
      
    - name: Install Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.8'  
  
    - name: Install pylint
      run: pip install pylint mypy

    # - name: Tag and Push Docker image to GCR
    #   run: |
    #      docker pull nginx
    
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: "nginx"
        format: 'txt'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'  # Scanning for all severity levels
        exit-code: '0'   # Ensures the job does not fail on vulnerabilities
        output: 'trivy-report.txt'
         
