name: Test Self-Hosted Runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run shell command
      run: echo "Self-hosted runner is working!"
      
    - name: Install Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.8'  
  
    - name: Install pylint
      run: pip install pylint mypy

    - name: Tag and Push Docker image to GCR
      run: |
         docker pull nginx
         
