name: Test Self-Hosted Runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run shell command
      run: echo "Self-hosted runner is working!"
